name: Build Base Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.4'
            architecture: linux/amd64
            is_latest: true
          - php_version: '8.4'
            architecture: linux/arm64
            is_latest: true
          - php_version: '8.3'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.3'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.2'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.2'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.1'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.1'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.0'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.0'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.4'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.4'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.3'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.3'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.2'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.2'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.1'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.1'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.0'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.0'
            architecture: linux/arm64
            is_latest: false
          - php_version: '5.6'
            architecture: linux/amd64
            is_latest: false
          - php_version: '5.6'
            architecture: linux/arm64
            is_latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare architecture name
        id: prep
        run: echo "arch_short=${ARCH##*/}" >> $GITHUB_OUTPUT
        env:
          ARCH: ${{ matrix.architecture }}

      - name: Build PHP Base Image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          file: flavors/vanilla/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/php-cli:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}

      - name: Test php image to check if version matches
        run: |
          docker run --rm --platform=${{ matrix.architecture }} fbraz3/php-cli:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }} -v | grep -q "${{ matrix.php_version }}" || exit 1
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Push PHP Base Image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          file: flavors/vanilla/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/php-cli:${{ matrix.php_version }}
            fbraz3/php-base:${{ matrix.php_version }}
            ${{ matrix.is_latest && 'fbraz3/php-cli:latest' || '' }}
            ${{ matrix.is_latest && 'fbraz3/php-base:latest' || '' }}