name: Test Docker

on:
  workflow_dispatch:

env:
  LOCAL_REGISTRY: 127.0.0.1:5000
  REMOTE_REGISTRY: docker.io

jobs:
  build_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.2'
            architecture: linux/amd64
            is_latest: false
          #- php_version: '8.2'
          #  architecture: linux/arm64
          #  is_latest: false

    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare architecture name
        id: prep
        run: echo "arch_short=${ARCH##*/}" >> $GITHUB_OUTPUT
        env:
          ARCH: ${{ matrix.architecture }}

      - name: Build PHP Docker TEST image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          file: flavors/vanilla/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            ${{env.LOCAL_REGISTRY}}/fbraz3/php-cli:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}

      - name: Test php image to check if version matches
        run: |
          docker run --rm --platform=${{ matrix.architecture }} ${{env.LOCAL_REGISTRY}}/fbraz3/php-cli:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }} -v | grep -q "${{ matrix.php_version }}" || exit 1
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Build Phalcon TEST image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          file: flavors/phalcon/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            BUILD_ARCH=${{ steps.prep.outputs.arch_short }}
            REGISTRY=${{env.LOCAL_REGISTRY}}
          tags: |
            ${{env.LOCAL_REGISTRY}}/fbraz3/php-cli:${{ matrix.php_version }}-phalcon-${{ steps.prep.outputs.arch_short }}

      - name: Test php modules to ensure phalcon is loaded
        run: |
          docker run --rm --platform=${{ matrix.architecture }} ${{env.LOCAL_REGISTRY}}/fbraz3/php-cli:${{ matrix.php_version }}-phalcon-${{ steps.prep.outputs.arch_short }} -v | grep -q "${{ matrix.php_version }}" || exit 1
          docker run --rm --platform=${{ matrix.architecture }} ${{env.LOCAL_REGISTRY}}/fbraz3/php-cli:${{ matrix.php_version }}-phalcon-${{ steps.prep.outputs.arch_short }} -m | grep -q "phalcon" || exit 1
        env:
          PHP_VERSION: ${{ matrix.php_version }}

      - name: Run docker image ls to check if image is present
        run: |
          docker image ls -a
        
        
