name: Build Docker Image - phalcon

on:
  workflow_dispatch:
  schedule:
    - cron: '10 6 * * 0'

jobs:
  build_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.4'
            architecture: linux/amd64
            is_latest: true
          - php_version: '8.4'
            architecture: linux/arm64
            is_latest: true
          - php_version: '8.3'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.3'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.2'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.2'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.1'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.1'
            architecture: linux/arm64
            is_latest: false
          - php_version: '8.0'
            architecture: linux/amd64
            is_latest: false
          - php_version: '8.0'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.4'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.4'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.3'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.3'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.2'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.2'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.1'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.1'
            architecture: linux/arm64
            is_latest: false
          - php_version: '7.0'
            architecture: linux/amd64
            is_latest: false
          - php_version: '7.0'
            architecture: linux/arm64
            is_latest: false
          - php_version: '5.6'
            architecture: linux/amd64
            is_latest: false
          - php_version: '5.6'
            architecture: linux/arm64
            is_latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare architecture name
        id: prep
        run: echo "arch_short=${ARCH##*/}" >> $GITHUB_OUTPUT
        env:
          ARCH: ${{ matrix.architecture }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: docker-image-vanilla.yml
          workflow_conclusion: success
          name: php-base-${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}.tar
          path: ${{ runner.temp }}
          use_unzip: true

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/php-base-${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}.tar

      - name: Add image to Buildx cache
        run: |
          docker buildx imagetools create --tag fbraz3/php-base:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }} fbraz3/php-base:${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}    

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          file: builds/phalcon/Dockerfile
          push: true
          load: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            BUILD_ARCH=${{ steps.prep.outputs.arch_short }}
          tags: |
            fbraz3/php-base:phalcon-${{ matrix.php_version }}
            fbraz3/php-base:phalcon-${{ matrix.php_version }}-${{ steps.prep.outputs.arch_short }}
            ${{ matrix.is_latest && 'fbraz3/php-base:phalcon-latest' || '' }}
            ${{ matrix.is_latest && format('fbraz3/php-base:phalcon-latest-{0}', steps.prep.outputs.arch_short) || '' }}