name: Build Symfony Images

on:
  workflow_dispatch:
  schedule:
    - cron: '45 7 * * 0'

jobs:
  build_images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.4'
            is_latest: true
          - php_version: '8.3'
            is_latest: false
          - php_version: '8.2'
            is_latest: false
          - php_version: '8.1'
            is_latest: false
          - php_version: '8.0'
            is_latest: false
          - php_version: '7.4'
            is_latest: false
          - php_version: '7.3'
            is_latest: false
          - php_version: '7.2'
            is_latest: false
          - php_version: '7.1'
            is_latest: false
          - php_version: '7.0'
            is_latest: false
          - php_version: '5.6'
            is_latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # BUILD AMD64 IMAGE
      - name: Build and Push PHP Symfony Images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: flavors/symfony/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
              PHP_VERSION=${{ matrix.php_version }}
          tags: |
              fbraz3/symfony:${{ matrix.php_version }}-amd64

      - name: test amd64 image
        run: |
          docker run --rm --platform=linux/amd64 fbraz3/symfony:${{ matrix.php_version }}-amd64 -v
          docker run --rm --platform=linux/amd64 fbraz3/symfony:${{ matrix.php_version }}-amd64 -v 2>&1 | grep -q "symfony" || exit 1

      # BUILD ARM64 IMAGE
      - name: Build and Push PHP Symfony Images - arm64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: flavors/symfony/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
              PHP_VERSION=${{ matrix.php_version }}
          tags: |
              fbraz3/symfony:${{ matrix.php_version }}-arm64

      - name: test arm64 image
        run: |
          docker run --rm --platform=linux/arm64 fbraz3/symfony:${{ matrix.php_version }}-arm64 -v
          docker run --rm --platform=linux/arm64 fbraz3/symfony:${{ matrix.php_version }}-arm64 -v 2>&1 | grep -q "symfony" || exit 1

      # BUILD AND PUSH MULTI-ARCH IMAGE
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Symphony Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: flavors/symfony/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/symfony-cli:${{ matrix.php_version }}
            ${{ matrix.is_latest && 'fbraz3/symfony-cli:latest' || '' }}