name: Build Base Image

on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      architecture:
        required: true
        type: string
      is_latest:
        required: true
        type: boolean

jobs:
  build_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Base PHP Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.architecture }}
          context: .
          file: flavors/vanilla/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php_version }}
          tags: |
            fbraz3/php-cli:${{ inputs.php_version }}
            ${{ inputs.is_latest && 'fbraz3/php-cli:latest' || '' }}

      - name: Test php image to check if version matches
        run: |
          docker run --rm fbraz3/php-cli:${{ inputs.php_version }} -v | grep -q "${{ inputs.php_version }}" || exit 1
        env:
          PHP_VERSION: ${{ inputs.php_version }}

      - name: Push Base PHP Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.architecture }}
          context: .
          file: flavors/vanilla/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php_version }}
          tags: |
            fbraz3/php-cli:${{ inputs.php_version }}
            ${{ inputs.is_latest && 'fbraz3/php-cli:latest' || '' }}