name: Build WP-CLI Image

on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      architecture:
        required: true
        type: string
      is_latest:
        required: true
        type: boolean

jobs:
  build_wp_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build WP-CLI image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.architecture }}
          context: .
          file: flavors/wp-cli/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php_version }}
          tags: |
            fbraz3/wp-cli:${{ inputs.php_version }}
            ${{ inputs.is_latest && 'fbraz3/wp-cli:latest' || '' }}

      - name: Test WP-CLI to ensure it loads properly
        run: |
          docker run --rm fbraz3/wp-cli:${{ inputs.php_version }} --info || exit 1

      - name: Push WP-CLI image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.architecture }}
          context: .
          file: flavors/wp-cli/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php_version }}
          tags: |
            fbraz3/wp-cli:${{ inputs.php_version }}
            ${{ inputs.is_latest && 'fbraz3/wp-cli:latest' || '' }}